### ISSUE TITLE
Melhorar saida do resultado do juiz

### ISSUE THREAD

**Issue by felipeViana** [GokuITA/Athena#30]
Nao ta fazendo nova linha

melhorar a saida do diff (tem que ver como seria melhor)

**Comment by felipeViana** [comment]
Agora ja ta fazendo nova linha
pull: #31

**Comment by victorfonsec4** [comment]
o pull #36 melhora a saída para erro de compilação, mostrando diretório relativo para os arquivos em vez do diretório total

**Comment by victorfonsec4** [comment]
#103 mostra a saida bonita
